# C:\Users\..\AppData\Roaming\alacritty\alacritty.toml
working_directory = 'C:\Users'

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12

[font.normal]
family = "JetBrains Mono"

[scrolling]
history = 40000

[selection]
save_to_clipboard = true

[shell]
program = 'C:\Program Files\PowerShell\7\pwsh.exe'

[window]
dynamic_title = true
startup_mode = "Maximized"
