# if not running interactively, don't do anything
[ -z "$PS1" ] && return

HISTSIZE=2000
HISTFILESIZE=4000
# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary, update the values of LINES and COLUMNS.
shopt -s checkwinsize

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

if [ -z "$SSH_AUTH_SOCK" ]; then
    eval "$(ssh-agent -s)"
fi

# set a fancy color prompt with git info (if applicable)
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;33m\]\w\[\033[00m\] \[\033[01;36m\]$(git branch --show-current 2> /dev/null)\[\033[00m\]\$ '

set -o vi
export EDITOR=$(which nvim)

export LSCOLORS='ExGxFxdxCxDxDxBxBxExEx'
export CLICOLOR=1
export LD_LIBRARY_PATH=/usr/lib32:$LD_LIBRARY_PATH

cowsay $(fortune)
