alias c='clear'
alias grep='grep -i --color --exclude-dir=node_modules --exclude-dir=.git'
alias h='history'
alias httpd='python2 -m SimpleHTTPServer'
alias jp='python2 -m json.tool'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alFh'
alias lt='ls -lrt'
alias slb='screen -r -d leftbot || screen -S leftbot'
alias slt='screen -r -d lefttop || screen -S lefttop'
alias sr='screen -r -d right || screen -S right'
alias xclip='xclip -selection clipboard'
alias vim='nvim'
alias usepy2='sudo unlink /usr/bin/python && sudo link /usr/bin/python2 /usr/bin/python'
alias usepy3='sudo unlink /usr/bin/python && sudo link /usr/bin/python3 /usr/bin/python'
